language: ruby
cache: bundler
rvm: 
 - 2.0.0
 - 1.9.3
services: postgresql
install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq postgresql-contrib-9.1
before_script:
 - psql -c 'create database kodiak_test;' -U postgres
 - chmod +x ./script/ci/run_tests.sh
script: ./script/ci/run_tests.sh
