language: ruby
cache: bundler
rvm: 
 - 2.0.0
 - 1.9.3
services: postgresql
before_script:
 - psql -c 'create database kodiak_test;' -U postgres
 - RAILS_ENV=test bundle exec rake db:migrate
 - RAILS_ENV=test bundle exec rspec
