language: ruby
cache: bundler
addons:
  code_climate:
    repo_token: 3d255b2cfd37d4db29b81c8ec30c17bac274d5b062024b8254cba978134309ee 
rvm: 
 - 2.0.0
 - 1.9.3
services: postgresql
install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq postgresql-contrib-9.1
 - bundle install
before_script:
 - psql -c 'create database kodiak_test;' -U postgres
 - psql -U postgres kodiak_test < db/search_extensions.sql
 - chmod +x ./script/ci/run_tests.sh
script: ./script/ci/run_tests.sh
