development:
  adapter: postgresql
  database: kodiak_dev
  username: kodiak_dev
  password: kodiak_dev
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kodiak_test
  username: kodiak_test
  password: kodiak_test
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

