development:
  adapter: postgresql
  database: kodiak_dev
  username: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

test_local:
  adapter: postgresql
  database: kodiak_test
  username: postgres
  password:
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kodiak_test
  username: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

